#This playbbok will install HTTP server,wget and vim package using loops.

---
- hosts: localhost
  become: true
  tasks:
    - name: Install list of packages
      yum: name='{{item}}' state=present
      with_items:
       - httpd
       - wget
       - vim
       - zip
       - unzip  
...
